### ISSUE TITLE
RC and Devel Regressión: The system doesn't notify that there is a problem with the account when syncing

### ISSUE THREAD

**Issue by j2g2rp** [ubports/sync-monitor#27]
I was on devel testing a beta update of the calendar and I noticed that new events wasn't syncronize on N5
Tried also on RC on M10FHD, but didn't worked either.
I back to stable and when tried to sync a bubble notification appeared saying that there was a problem with the account
![imagen](https://user-images.githubusercontent.com/28528967/80321646-f8a23d80-881e-11ea-854d-6d2e5bbfbfb3.png)

Looks like that this is lost on devel and RC images, isn't it?
Almost forgot to say: the Stable version where it worked correctly was OTA11.

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/core/sync-monitor/-/issues/27

Sorry for your inconvenience.
