### ISSUE TITLE
translations on weblate are not complete

### ISSUE THREAD

**Issue by Danfro** [ubports/sync-monitor#45]
There are some strings from this repo missing on weblate. For instance all strings from the ["new account" page](https://github.com/ubports/sync-monitor/blob/xenial/accounts/plugin/qml/NewAccount.qml) are not there. This results in this page not being available translated. Maybe because this is a plugin?

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/core/sync-monitor/-/issues/45

Sorry for your inconvenience.
