### ISSUE TITLE
Refactor account handling

### ISSUE THREAD

**Issue by mardy** [ubports/sync-monitor#6]
While working on #5 I realized that the account handling code could be greatly improved. The hardcoding of provider names should be removed.

**Comment by NeoTheThird** [comment]
![do it](https://media.giphy.com/media/3o84sw9CmwYpAnRRni/giphy.gif)

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/core/sync-monitor/-/issues/6

Sorry for your inconvenience.
