### ISSUE TITLE
Feature Request: CardDAV plugin

### ISSUE THREAD

**Issue by idekovets** [ubports/sync-monitor#9]
Add CardDAV plugin, that adds support so Contacts can be synced with Owncloud/Nextcloud or any other Carddav Server.

Same: https://github.com/ubports/address-book-app/issues/3

**Comment by Danfro** [comment]
Is this issue here in sync-monitor already solved by #1 ? Then "only" addressbook app needs work to be done.

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/core/sync-monitor/-/issues/9

Sorry for your inconvenience.
